In [1]:
import numpy as np

In [2]:
a = np.zeros((2,4))

In [3]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
b = np.random.random_sample((2,3)) * 100

In [15]:
b

array([[86.96051856, 27.64822492, 27.65863043],
       [36.19193124, 89.02802316, 82.48587646]])

In [23]:
c = np.dot(a,a.T)

In [24]:
c

array([[11595.12110569, 10677.79495021],
       [10677.79495021, 10157.18294406]])

In [25]:
d = np.dot(np.array([1,2,3]),np.array([4,5,6]))

In [27]:
print(d)

32


In [29]:
f = a.reshape(-1,2)

In [30]:
f

array([[25.78176812, 32.51262875],
       [99.36473474, 38.51947632],
       [37.94756848, 85.04948521]])

In [31]:
g = b.reshape(2,-1)

In [32]:
g

array([[86.96051856, 27.64822492, 27.65863043],
       [36.19193124, 89.02802316, 82.48587646]])

In [37]:
g.shape
g[0].shape

(3,)

In [38]:
g[0][1].shape

()

In [39]:
import time as t

In [42]:
vec1 = np.random.rand(100000)
vec2 = np.random.rand(100000)

In [53]:
tic = t.time()
dotpro = np.dot(vec1,vec2)
toc = t.time()
print(f"Dot product is {dotpro:.2f},  and time taken is {1000* (toc-tic):.1f} ms")

Dot product is 24944.72,  and time taken is 0.0 ms
