In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
print("Shape of a: ",a.shape)
print("Dimension/axis of a: ",a.ndim)
print("Bits of each item in a: ",a.itemsize)
print("Size of a: ",a.size)

Shape of a:  (3, 5)
Dimension/axis of a:  2
Bits of each item in a:  4
Size of a:  15


-  #### Array Creation

In [24]:
a = np.array([1,2,3])
print("a: ",a," Datatype of array ",a.dtype)

b = np.array([[1,2,3],[4,5,6]],dtype =complex)
print("b: ",b," Datatype of array ",b.dtype)

np.zeros((3,4))
np.ones((2,2))
np.empty((2,3))   #Creates an array on state of memory
np.arange(1,2,0.2)

a:  [1 2 3]  Datatype of array  int32
b:  [[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]  Datatype of array  complex128


array([1. , 1.2, 1.4, 1.6, 1.8])

- ###  Matrix Multiplication

In [59]:
a = np.arange(4).reshape(2,2)
b = np.arange(5,9,1).reshape(2,2)

c = a*b   #Element by Element Multiplication
c = a@b
c = a.dot(b)
c = np.dot(a,b)
c
rg = np.random.default_rng(1)
rg.random((2,4))

array([[0.51182162, 0.9504637 , 0.14415961, 0.94864945],
       [0.31183145, 0.42332645, 0.82770259, 0.40919914]])

In [61]:
np.array([2.,-1.,4.])

array([ 2., -1.,  4.])