In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape

(3,)

In [5]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
print(arr2[0,1])

2


In [7]:
arr2.shape

(2, 3)

In [8]:
arr2.size

6

In [9]:
str_arr = np.array(["Hello",True,1])
str_arr
type(str_arr)

numpy.ndarray

In [10]:
arr2.ndim

2

In [11]:
arr2.data

In [12]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
np.append(arr2,1)

array([1, 2, 3, 4, 5, 6, 1])

In [14]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.delete(arr2,1,0)

array([[1, 2, 3]])

In [16]:
# For 2D array have to follow this convention

In [39]:
arr2d = np.array([[1,2,3],[2,4,6]])
col_insert = [[4],[5]]
new_arr2d = np.append(arr2d, col_insert,1)
new_arr2d

#same goes for delete
new_arr2d = np.delete(new_arr2d,1, 0)
new_arr2d

array([[1, 2, 3, 4]])

# Create Some Arrays builtin

In [49]:
x = np.zeros(2)
x

array([0., 0.])

In [50]:
y = np.zeros((2,3) ,dtype = int)
y

array([[0, 0, 0],
       [0, 0, 0]])

In [52]:
a = np.ones((4,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
b = np.ones((4,3,2))
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [60]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.arange(1,5)

array([1, 2, 3, 4])

In [62]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [64]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [77]:
np.linspace(1.,4.,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [79]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [81]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [82]:
np.random.random()

0.14433593683383728

In [89]:
np.random.randint(3)

1

# Math Operations

In [92]:
x= np.array([[1,2],[3,4]])
y= np.array([[5,6],[7,8]])

In [93]:
x + y

array([[ 6,  8],
       [10, 12]])

In [96]:
z = np.add(x,y)
z

array([[ 6,  8],
       [10, 12]])

In [97]:
np.subtract(z,x)

array([[5, 6],
       [7, 8]])

In [99]:
x * y

array([[ 5, 12],
       [21, 32]])

In [100]:
x ** y

array([[    1,    64],
       [ 2187, 65536]])

In [101]:
x // y

array([[0, 0],
       [0, 0]])

In [102]:
np.sqrt(z)

array([[2.44948974, 2.82842712],
       [3.16227766, 3.46410162]])

In [103]:
v = np.array([9,10])

In [104]:
w =  np.array([11,13])

In [109]:
v.dot(w)

np.int64(229)

In [110]:
np.dot(x,v)

array([29, 67])

In [111]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [112]:
x.T

array([[1, 3],
       [2, 4]])

In [113]:
np.sum(x)

np.int64(10)

In [115]:
np.sum(x,axis = 1)

array([3, 7])